- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserFragment.java
- app/src/main/java/fi/aalto/legroup/achso/playback/VideoPlayerActivity.java
Fixes a crash that occurs when browsing videos.
> Release v1.0.2.

- app/src/main/AndroidManifest.xml
- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/playback/VideoPlayerActivity.java
- app/src/main/java/fi/aalto/legroup/achso/views/MarkedSeekBar.java
- app/src/main/res/values/strings.xml
Addresses JIRA ticket `ACH-12`.
> Miscellaneous cleanup

- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/playback/VideoPlayerActivity.java
- app/src/main/java/fi/aalto/legroup/achso/playback/VideoPlayerFragment.java
- app/src/main/java/fi/aalto/legroup/achso/views/Marker.java
- Fixes a crash when recording on some Samsung devices
- Improves annotation editing
> Release v1.0.4.

- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/playback/annotations/AnnotationRenderer.java
- Fixes an exception when releasing the annotation renderer.
- Stores video builders across state changes.
> Release v1.0.5.

- app/src/main/java/fi/aalto/legroup/achso/authoring/VideoCreatorService.java
- app/src/main/java/fi/aalto/legroup/achso/playback/annotations/AnnotationRenderer.java
> Release v1.0.6.

- app/src/main/res/values-de/strings.xml
> Updated German translation.

- app/build.gradle
- app/proguard-rules.pro
- app/src/main/java/fi/aalto/legroup/achso/support/AboutDialogFragment.java
- app/src/main/java/fi/aalto/legroup/achso/support/FeedbackDialogFragment.java
- app/src/main/res/layout/dialog_about.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
- Improved German translation
- Improved user interface
- Bug fixes
> Release v1.0.7.

- app/src/main/res/values-et/strings.xml
ACH-67 Update Estonian translation
New translations by Pjotr
> ACH-67 Update Estonian translation New translations by Pjotr

- app/src/main/java/fi/aalto/legroup/achso/playback/VideoPlayerFragment.java
- app/src/main/java/fi/aalto/legroup/achso/playback/utilities/FrameworkOrientationReader.java
- app/src/main/java/fi/aalto/legroup/achso/playback/utilities/Mp4ParserOrientationReader.java
- app/src/main/java/fi/aalto/legroup/achso/playback/utilities/VideoOrientationPatcher.java
- Split orientation reading into separate files
- Better comments
- More reliable track handling
> Improve video orientation detection.

- app/src/main/java/fi/aalto/legroup/achso/playback/annotations/AnnotationRenderer.java
ACH-38 Time for reading annotations should be longer
Annotations should stay on the screen for a longer period of time
> ACH-38 Time for reading annotations should be longer

- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/app/AppCache.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/Authenticator.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/LoginManager.java
- app/src/main/java/fi/aalto/legroup/achso/playback/utilities/VideoOrientationPatcher.java
- app/src/main/java/fi/aalto/legroup/achso/views/adapters/VideoGridAdapter.java
- Better context management.
- Wider usage of convenience methods.
> Internal cleanup.

- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/playback/VideoPlayerFragment.java
> Control the media volume instead of the ringer.

- app/src/main/java/fi/aalto/legroup/achso/app/AppCache.java
These were left over from the old sharing behaviour.
> Clear older temporary .achso files.

- app/build.gradle
- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/app/AppPreferences.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/OIDCConfig.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/strategies/ClViTra2Strategy.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/strategies/SssStrategy.java
- app/src/main/java/fi/aalto/legroup/achso/support/MobSosDialogFragment.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
The URL can be set in the settings screen. It defaults to the one set in secrets.xml.
> Make the Layers API endpoint configurable.

- app/src/main/AndroidManifest.xml
- app/src/main/res/drawable/floating_controls_background.xml
- app/src/main/res/drawable/material_button_fallback_dark.xml
- app/src/main/res/drawable/material_button_fallback_dark_normal.xml
- app/src/main/res/drawable/material_button_fallback_dark_pressed.xml
- app/src/main/res/drawable/top_scrim.xml
- app/src/main/res/layout/activity_video_player.xml
- app/src/main/res/layout/fragment_video_information.xml
- app/src/main/res/layout/partial_annotation_controls.xml
- app/src/main/res/layout/partial_playback_controls.xml
- app/src/main/res/layout/partial_toolbar.xml
- app/src/main/res/layout/partial_toolbar_with_nav_button.xml
- app/src/main/res/layout/partial_toolbar_with_nav_button_transparent.xml
- app/src/main/res/menu/menu_player.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
Now shows the correct text colour in the UI with appropriate Material
button styles.
> Fix dark theming on Android 20 and lower.

- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/app/AppAnalytics.java
- app/src/main/java/fi/aalto/legroup/achso/app/AppPreferences.java
- app/src/main/java/fi/aalto/legroup/achso/authoring/VideoCreatorService.java
- app/src/main/res/values/.secrets.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
Still needs to ask the user at first launch. I’ve got some ideas for that so let’s do it separately.
> Add basic Google Analytics support.

- app/build.gradle
- app/src/main/java/fi/aalto/legroup/achso/authoring/QRHelper.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserFragment.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/DetailActivity.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/DetailDialogFragment.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/DetailFragment.java
- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerActivity.java
- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerFragment.java
- app/src/main/java/fi/aalto/legroup/achso/storage/local/ExportService.java
- app/src/main/java/fi/aalto/legroup/achso/support/FeedbackDialogFragment.java
- app/src/main/java/fi/aalto/legroup/achso/support/MobSosDialogFragment.java
- app/src/main/java/fi/aalto/legroup/achso/utilities/BaseActivity.java
These could later be improved with actions like “undo” or “retry.”
> Snackbars, snackbars everywhere!

- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerActivity.java
When editing an annotation it should not be possible to create new ones.
Fixes ACH-105.
> Disable annotation creation when editing

- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerActivity.java
- app/src/main/res/layout/activity_player.xml
> Fix dragging annotations while editing.

- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/storage/AbstractVideoRepository.java
- app/src/main/java/fi/aalto/legroup/achso/storage/CachedVideoRepository.java
Added `CachedVideoRepository` dectorator to re-add caching behavior.
> Re-add caching to local video repository

- app/src/main/java/fi/aalto/legroup/achso/authentication/OIDCUtils.java
> Fix a crash when the server returns a null token.

- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
On pause switch self to a `PendingRepositoryUpdateListener` but keep listening for `VideoRepositoryUpdatedEvent`s with that and handle them later when resumed.
> Update the browser view even when update events come when paused

- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserFragment.java
- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerActivity.java
- app/src/main/res/layout/partial_playback_controls.xml
- app/src/main/res/menu/activity_browser.xml
- app/src/main/res/menu/activity_browser_action_mode.xml
- app/src/main/res/menu/activity_player.xml
- [blocker] Proper path to achrails
- [important] Action icon order, visibility and logic improvements.
> Release v1.3.2

- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/app/AppPreferences.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/Authenticator.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/AuthorizationActivity.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/LoginActivity.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/LoginManager.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/LoginStateEvent.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/OIDCConfig.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/OIDCNotReadyException.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/settings/SettingsFragment.java
- app/src/main/java/fi/aalto/legroup/achso/sharing/SharingActivity.java
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values/.secrets.xml
- app/src/main/res/values/strings.xml
- Add support for Layers Boxes with multiple accounts
> Release v1.3.4

- app/build.gradle
- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/LoginActivity.java
- app/src/main/java/fi/aalto/legroup/achso/authentication/LoginManager.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/entities/Annotation.java
- app/src/main/java/fi/aalto/legroup/achso/entities/OptimizedVideo.java
- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerActivity.java
- app/src/main/java/fi/aalto/legroup/achso/storage/CombinedVideoRepository.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/UploadService.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/strategies/AchRailsStrategy.java
- app/src/main/res/values/strings.xml
- Add features to help logging (annotation timestamps, view counts)
- Remove cached videos when switching users
- Support ARG_LAYERS_BOX_URL
- Redirect user to settings if no permissions
> Release v1.3.5

- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserFragment.java
- app/src/main/java/fi/aalto/legroup/achso/views/adapters/VideoGridAdapter.java
* Fix some crashes
* use Go video transcoder for handling videos
> Release v1.3.1

- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerActivity.java
- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerFragment.java
- app/src/main/res/drawable/floating_controls_background.xml
- app/src/main/res/layout/activity_player.xml
- app/src/main/res/layout/partial_annotation_controls.xml
- app/src/main/res/layout/partial_playback_controls.xml
* Add single-tap annotation, like on iOS
> Release v1.4.1

- app/src/main/java/fi/aalto/legroup/achso/app/App.java
- app/src/main/java/fi/aalto/legroup/achso/authoring/ExportDialogFragment.java
- app/src/main/java/fi/aalto/legroup/achso/authoring/ExportHelper.java
- app/src/main/java/fi/aalto/legroup/achso/authoring/QRHelper.java
- app/src/main/java/fi/aalto/legroup/achso/authoring/VideoCreatorService.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserFragment.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/DetailFragment.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/SearchActivity.java
- app/src/main/java/fi/aalto/legroup/achso/entities/OptimizedVideo.java
- app/src/main/java/fi/aalto/legroup/achso/entities/Video.java
- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerActivity.java
- app/src/main/java/fi/aalto/legroup/achso/storage/CombinedVideoRepository.java
- app/src/main/java/fi/aalto/legroup/achso/storage/VideoInfoRepository.java
- app/src/main/java/fi/aalto/legroup/achso/storage/VideoRepository.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/UploadService.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/VideoHost.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/strategies/AchRailsStrategy.java
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/fragment_export.xml
- app/src/main/res/menu/activity_browser.xml
- app/src/main/res/menu/activity_browser_action_mode.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values/.secrets.xml
- app/src/main/res/values/strings.xml
- build.gradle
- Improve usability in video player and annotating
- Add visible username and email to kebab bar
- Add export videos feature
- Add online search
- Clearer translations in some places
> Release v1.5.0

- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserFragment.java
- Fix accidental debug email leftover
> Release v1.5.1

- app/src/main/java/fi/aalto/legroup/achso/authentication/LoginManager.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/DetailActivity.java
- app/src/main/java/fi/aalto/legroup/achso/storage/CombinedVideoRepository.java
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle
Revert back to old video recording flow, fix some edge cases with video ownership
> Release v1.8.2

- app/src/main/java/fi/aalto/legroup/achso/storage/CombinedVideoRepository.java
Add hotfix for checking whether or not user can share to a group
> Release v1.8.3

- app/build.gradle
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserActivity.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/BrowserFragment.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/DetailActivity.java
- app/src/main/java/fi/aalto/legroup/achso/browsing/DetailFragment.java
- app/src/main/java/fi/aalto/legroup/achso/playback/PlayerActivity.java
- app/src/main/java/fi/aalto/legroup/achso/storage/CombinedVideoRepository.java
- app/src/main/java/fi/aalto/legroup/achso/storage/VideoRepository.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/VideoHost.java
- app/src/main/java/fi/aalto/legroup/achso/storage/remote/upload/UploadService.java
- app/src/main/java/fi/aalto/legroup/achso/views/MarkedSeekBar.java
- app/src/main/java/fi/aalto/legroup/achso/views/adapters/GroupsListAdapter.java
- app/src/main/java/fi/aalto/legroup/achso/views/adapters/VideoGridAdapter.java
- app/src/main/res/layout/fragment_information.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-fi/strings.xml
- app/src/main/res/values/strings.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Multi-video sharing and uploading
- Show colors in annotation timeline
> Release 1.9.0
